spring.application.name=notification-service

# ===============================
# Server
# ===============================
server.port=${PORT:8086}

# ===============================
# Mail (ENV BASED)
# ===============================
# ===============================
# Mail (ENV BASED)
# ===============================
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}

spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS_ENABLE:true}


# ===============================
# Thymeleaf
# ===============================
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

# ===============================
# Spring Cloud (Disabled)
# ===============================
spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false

# ===============================
# Logging
# ===============================
logging.level.root=INFO
logging.level.com.carrental.notificationservice=INFO
